import type {
  OverviewMetric,
  StockMovementData,
  InventoryHealthData,
  AttentionItem,
  TopMovingProduct,
  QuickActionItem,
} from "./types";

export const MOCK_OVERVIEW_METRICS: OverviewMetric[] = [
  {
    id: "products",
    label: "Total Produk",
    value: "1.428",
    rawValue: 1428,
    change: "+24 bulan ini",
    trend: "up",
    supportingText: "Di 8 kategori",
    iconName: "products",
    variant: "default",
  },
  {
    id: "inventory_value",
    label: "Nilai Inventaris",
    value: "$248.650",
    rawValue: 248650,
    change: "+5,4% vs bulan lalu",
    trend: "up",
    supportingText: "Rata-rata biaya $174,12",
    iconName: "value",
    variant: "default",
  },
  {
    id: "low_stock",
    label: "Stok Menipis",
    value: "14",
    rawValue: 14,
    change: "3 item dipesan",
    trend: "neutral",
    supportingText: "Di bawah batas reorder min",
    iconName: "low_stock",
    variant: "warning",
  },
  {
    id: "out_of_stock",
    label: "Stok Habis",
    value: "3",
    rawValue: 3,
    change: "Perlu restok segera",
    trend: "down",
    supportingText: "Nol unit tersedia",
    iconName: "out_of_stock",
    variant: "destructive",
  },
];

export const MOCK_STOCK_MOVEMENT_7D: StockMovementData = {
  timeframe: "7d",
  totalIn: 1240,
  totalOut: 985,
  netChange: 255,
  data: [
    { period: "Sen", stockIn: 180, stockOut: 120 },
    { period: "Sel", stockIn: 95, stockOut: 140 },
    { period: "Rab", stockIn: 240, stockOut: 190 },
    { period: "Kam", stockIn: 130, stockOut: 110 },
    { period: "Jum", stockIn: 320, stockOut: 215 },
    { period: "Sab", stockIn: 165, stockOut: 130 },
    { period: "Min", stockIn: 110, stockOut: 80 },
  ],
};

export const MOCK_STOCK_MOVEMENT_30D: StockMovementData = {
  timeframe: "30d",
  totalIn: 5420,
  totalOut: 4680,
  netChange: 740,
  data: [
    { period: "Minggu 1", stockIn: 1180, stockOut: 980 },
    { period: "Minggu 2", stockIn: 1450, stockOut: 1240 },
    { period: "Minggu 3", stockIn: 1390, stockOut: 1180 },
    { period: "Minggu 4", stockIn: 1400, stockOut: 1280 },
  ],
};

export const MOCK_INVENTORY_HEALTH: InventoryHealthData = {
  totalProducts: 1428,
  healthScore: 88,
  healthy: {
    count: 1248,
    percentage: 87.4,
    value: 221800,
  },
  lowStock: {
    count: 154,
    percentage: 10.8,
    value: 24350,
  },
  outOfStock: {
    count: 26,
    percentage: 1.8,
    value: 2500,
  },
};

export const MOCK_ATTENTION_ITEMS: AttentionItem[] = [
  {
    id: "att-1",
    sku: "ELEC-ESP-32",
    name: "ESP32-WROOM-32D Microcontroller Module",
    category: "Elektronik",
    currentStock: 0,
    minStock: 50,
    unit: "pcs",
    status: "out_of_stock",
    warehouse: "Gudang Utama (WH-1)",
    lastRestocked: "14 hari lalu",
  },
  {
    id: "att-2",
    sku: "MECH-BRG-608",
    name: "Industrial Ball Bearing 608RS (8x22x7mm)",
    category: "Mekanikal",
    currentStock: 0,
    minStock: 100,
    unit: "pcs",
    status: "out_of_stock",
    warehouse: "Gudang Timur (WH-2)",
    lastRestocked: "21 hari lalu",
  },
  {
    id: "att-3",
    sku: "ALUM-EXT-2020",
    name: "T-Slot Aluminum Extrusion 2020 (1000mm)",
    category: "Struktural",
    currentStock: 0,
    minStock: 30,
    unit: "batang",
    status: "out_of_stock",
    warehouse: "Gudang Utama (WH-1)",
    lastRestocked: "18 hari lalu",
  },
  {
    id: "att-4",
    sku: "MOTR-STP-17",
    name: "NEMA 17 Stepper Motor 42BYGH",
    category: "Motor",
    currentStock: 4,
    minStock: 25,
    unit: "unit",
    status: "low_stock",
    warehouse: "Gudang Utama (WH-1)",
    lastRestocked: "8 hari lalu",
  },
  {
    id: "att-5",
    sku: "BATT-LION-1865",
    name: "Rechargeable Li-ion Cell 18650 3.7V 3000mAh",
    category: "Daya",
    currentStock: 12,
    minStock: 80,
    unit: "sel",
    status: "low_stock",
    warehouse: "Gudang Timur (WH-2)",
    lastRestocked: "5 hari lalu",
  },
  {
    id: "att-6",
    sku: "THRM-PST-5G",
    name: "High-Performance Thermal Paste 5g Syringe",
    category: "Kebutuhan",
    currentStock: 8,
    minStock: 40,
    unit: "tabung",
    status: "low_stock",
    warehouse: "Gudang Utama (WH-1)",
    lastRestocked: "3 hari lalu",
  },
];

export const MOCK_TOP_MOVING_PRODUCTS: TopMovingProduct[] = [
  {
    id: "top-1",
    sku: "CABL-USBC-2M",
    name: "Braided USB-C to USB-C Cable 100W 2m",
    category: "Kabel & Adaptor",
    movementQty: 480,
    stockIn: 300,
    stockOut: 180,
    currentStock: 240,
    unit: "pcs",
    turnoverRate: "8.4x",
  },
  {
    id: "top-2",
    sku: "FILA-PLA-BLK",
    name: "PLA+ 3D Printer Filament 1.75mm Black 1kg",
    category: "Pencetakan 3D",
    movementQty: 395,
    stockIn: 250,
    stockOut: 145,
    currentStock: 180,
    unit: "gulungan",
    turnoverRate: "7.1x",
  },
  {
    id: "top-3",
    sku: "FAST-M3-SS",
    name: "M3 Stainless Steel Socket Head Screw Kit (500pcs)",
    category: "Pengencang",
    movementQty: 310,
    stockIn: 200,
    stockOut: 110,
    currentStock: 95,
    unit: "kit",
    turnoverRate: "6.5x",
  },
  {
    id: "top-4",
    sku: "TOOL-PRC-24",
    name: "Precision Magnetic Screwdriver Set (24 Bits)",
    category: "Perkakas",
    movementQty: 265,
    stockIn: 150,
    stockOut: 115,
    currentStock: 74,
    unit: "set",
    turnoverRate: "5.8x",
  },
  {
    id: "top-5",
    sku: "SENS-ENV-BME",
    name: "BME280 Temperature Humidity Sensor Module",
    category: "Sensor",
    movementQty: 220,
    stockIn: 140,
    stockOut: 80,
    currentStock: 115,
    unit: "pcs",
    turnoverRate: "5.2x",
  },
];

export const MOCK_QUICK_ACTIONS: QuickActionItem[] = [
  {
    id: "add-product",
    title: "Tambah Produk",
    description: "Daftarkan produk baru dengan SKU & barcode",
    icon: "plus",
    badge: "Cepat",
  },
  {
    id: "stock-in",
    title: "Stok Masuk",
    description: "Terima pengiriman pembelian masuk",
    icon: "arrow-down",
    badge: "Masuk",
  },
  {
    id: "stock-out",
    title: "Stok Keluar",
    description: "Catat pengeluaran, penjualan atau penggunaan",
    icon: "arrow-up",
    badge: "Keluar",
  },
  {
    id: "transfer-stock",
    title: "Transfer Stok",
    description: "Pindahkan inventaris antar gudang",
    icon: "transfer",
    badge: "Internal",
  },
];
