import type {
  OverviewMetric,
  StockMovementData,
  InventoryHealthData,
  AttentionItem,
  TopMovingProduct,
  QuickActionItem,
} from "./types";

export const MOCK_OVERVIEW_METRICS: OverviewMetric[] = [
  {
    id: "products",
    label: "Total Products",
    value: "1,428",
    rawValue: 1428,
    change: "+24 this month",
    trend: "up",
    supportingText: "Across 8 categories",
    iconName: "products",
    variant: "default",
  },
  {
    id: "inventory_value",
    label: "Inventory Value",
    value: "$248,650",
    rawValue: 248650,
    change: "+5.4% vs last month",
    trend: "up",
    supportingText: "Avg item cost $174.12",
    iconName: "value",
    variant: "default",
  },
  {
    id: "low_stock",
    label: "Low Stock",
    value: "14",
    rawValue: 14,
    change: "3 items ordered",
    trend: "neutral",
    supportingText: "Below minimum reorder level",
    iconName: "low_stock",
    variant: "warning",
  },
  {
    id: "out_of_stock",
    label: "Out of Stock",
    value: "3",
    rawValue: 3,
    change: "Immediate restock needed",
    trend: "down",
    supportingText: "Zero units available",
    iconName: "out_of_stock",
    variant: "destructive",
  },
];

export const MOCK_STOCK_MOVEMENT_7D: StockMovementData = {
  timeframe: "7d",
  totalIn: 1240,
  totalOut: 985,
  netChange: 255,
  data: [
    { period: "Mon", stockIn: 180, stockOut: 120 },
    { period: "Tue", stockIn: 95, stockOut: 140 },
    { period: "Wed", stockIn: 240, stockOut: 190 },
    { period: "Thu", stockIn: 130, stockOut: 110 },
    { period: "Fri", stockIn: 320, stockOut: 215 },
    { period: "Sat", stockIn: 165, stockOut: 130 },
    { period: "Sun", stockIn: 110, stockOut: 80 },
  ],
};

export const MOCK_STOCK_MOVEMENT_30D: StockMovementData = {
  timeframe: "30d",
  totalIn: 5420,
  totalOut: 4680,
  netChange: 740,
  data: [
    { period: "Week 1", stockIn: 1180, stockOut: 980 },
    { period: "Week 2", stockIn: 1450, stockOut: 1240 },
    { period: "Week 3", stockIn: 1390, stockOut: 1180 },
    { period: "Week 4", stockIn: 1400, stockOut: 1280 },
  ],
};

export const MOCK_INVENTORY_HEALTH: InventoryHealthData = {
  totalProducts: 1428,
  healthScore: 88,
  healthy: {
    count: 1248,
    percentage: 87.4,
    value: 221800,
  },
  lowStock: {
    count: 154,
    percentage: 10.8,
    value: 24350,
  },
  outOfStock: {
    count: 26,
    percentage: 1.8,
    value: 2500,
  },
};

export const MOCK_ATTENTION_ITEMS: AttentionItem[] = [
  {
    id: "att-1",
    sku: "ELEC-ESP-32",
    name: "ESP32-WROOM-32D Microcontroller Module",
    category: "Electronics",
    currentStock: 0,
    minStock: 50,
    unit: "pcs",
    status: "out_of_stock",
    warehouse: "Main Hub (WH-1)",
    lastRestocked: "14 days ago",
  },
  {
    id: "att-2",
    sku: "MECH-BRG-608",
    name: "Industrial Ball Bearing 608RS (8x22x7mm)",
    category: "Mechanical",
    currentStock: 0,
    minStock: 100,
    unit: "pcs",
    status: "out_of_stock",
    warehouse: "East Annex (WH-2)",
    lastRestocked: "21 days ago",
  },
  {
    id: "att-3",
    sku: "ALUM-EXT-2020",
    name: "T-Slot Aluminum Extrusion 2020 (1000mm)",
    category: "Structural",
    currentStock: 0,
    minStock: 30,
    unit: "bars",
    status: "out_of_stock",
    warehouse: "Main Hub (WH-1)",
    lastRestocked: "18 days ago",
  },
  {
    id: "att-4",
    sku: "MOTR-STP-17",
    name: "NEMA 17 Stepper Motor 42BYGH",
    category: "Motors",
    currentStock: 4,
    minStock: 25,
    unit: "units",
    status: "low_stock",
    warehouse: "Main Hub (WH-1)",
    lastRestocked: "8 days ago",
  },
  {
    id: "att-5",
    sku: "BATT-LION-1865",
    name: "Rechargeable Li-ion Cell 18650 3.7V 3000mAh",
    category: "Power",
    currentStock: 12,
    minStock: 80,
    unit: "cells",
    status: "low_stock",
    warehouse: "East Annex (WH-2)",
    lastRestocked: "5 days ago",
  },
  {
    id: "att-6",
    sku: "THRM-PST-5G",
    name: "High-Performance Thermal Paste 5g Syringe",
    category: "Consumables",
    currentStock: 8,
    minStock: 40,
    unit: "tubes",
    status: "low_stock",
    warehouse: "Main Hub (WH-1)",
    lastRestocked: "3 days ago",
  },
];

export const MOCK_TOP_MOVING_PRODUCTS: TopMovingProduct[] = [
  {
    id: "top-1",
    sku: "CABL-USBC-2M",
    name: "Braided USB-C to USB-C Cable 100W 2m",
    category: "Cables & Adapters",
    movementQty: 480,
    stockIn: 300,
    stockOut: 180,
    currentStock: 240,
    unit: "pcs",
    turnoverRate: "8.4x",
  },
  {
    id: "top-2",
    sku: "FILA-PLA-BLK",
    name: "PLA+ 3D Printer Filament 1.75mm Black 1kg",
    category: "3D Printing",
    movementQty: 395,
    stockIn: 250,
    stockOut: 145,
    currentStock: 180,
    unit: "spools",
    turnoverRate: "7.1x",
  },
  {
    id: "top-3",
    sku: "FAST-M3-SS",
    name: "M3 Stainless Steel Socket Head Screw Kit (500pcs)",
    category: "Fasteners",
    movementQty: 310,
    stockIn: 200,
    stockOut: 110,
    currentStock: 95,
    unit: "kits",
    turnoverRate: "6.5x",
  },
  {
    id: "top-4",
    sku: "TOOL-PRC-24",
    name: "Precision Magnetic Screwdriver Set (24 Bits)",
    category: "Tools",
    movementQty: 265,
    stockIn: 150,
    stockOut: 115,
    currentStock: 74,
    unit: "sets",
    turnoverRate: "5.8x",
  },
  {
    id: "top-5",
    sku: "SENS-ENV-BME",
    name: "BME280 Temperature Humidity Sensor Module",
    category: "Sensors",
    movementQty: 220,
    stockIn: 140,
    stockOut: 80,
    currentStock: 115,
    unit: "pcs",
    turnoverRate: "5.2x",
  },
];

export const MOCK_QUICK_ACTIONS: QuickActionItem[] = [
  {
    id: "add-product",
    title: "Add Product",
    description: "Register new item with SKU & barcode",
    icon: "plus",
    badge: "Quick",
  },
  {
    id: "stock-in",
    title: "Stock In",
    description: "Receive incoming purchase shipment",
    icon: "arrow-down",
    badge: "Inbound",
  },
  {
    id: "stock-out",
    title: "Stock Out",
    description: "Record dispatch, sales or usage",
    icon: "arrow-up",
    badge: "Outbound",
  },
  {
    id: "transfer-stock",
    title: "Transfer Stock",
    description: "Move inventory between warehouses",
    icon: "transfer",
    badge: "Internal",
  },
];
