import type { PurchaseOrder } from "./types";

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-101",
    poNumber: "PO-2026-001",
    supplierId: "sup-1",
    supplierName: "Nvidia Global Logistics",
    supplierTier: "Tier 1 Preferred",
    destinationWarehouseId: "wh-1",
    destinationWarehouseName: "Gudang Utama Jakarta",
    status: "PARTIALLY_RECEIVED",
    orderDate: "2026-08-01",
    expectedDeliveryDate: "2026-08-15",
    totalCost: 18500,
    lineItems: [
      {
        id: "li-1",
        productId: "prod-1",
        productName: "NVIDIA RTX 4090 GPU",
        sku: "GPU-NV-4090",
        orderedQuantity: 10,
        receivedQuantity: 6,
        unitCost: 1600,
      },
      {
        id: "li-2",
        productId: "prod-2",
        productName: "Intel i9 14900K Processor",
        sku: "CPU-INT-14900K",
        orderedQuantity: 5,
        receivedQuantity: 5,
        unitCost: 500,
      },
    ],
    receipts: [
      {
        id: "rc-1",
        poId: "po-101",
        receivedAt: "2026-08-08 10:30",
        warehouseId: "wh-1",
        warehouseName: "Gudang Utama Jakarta",
        items: [
          { sku: "GPU-NV-4090", productName: "NVIDIA RTX 4090 GPU", quantityReceived: 6 },
          { sku: "CPU-INT-14900K", productName: "Intel i9 14900K Processor", quantityReceived: 5 },
        ],
        notes: "Batch 1 arrived in good condition. Remaining 4 GPUs pending vendor backorder.",
      },
    ],
    notes: "Expedited shipping requested for GPU units.",
  },
  {
    id: "po-102",
    poNumber: "PO-2026-002",
    supplierId: "sup-2",
    supplierName: "Logitech Official Direct",
    supplierTier: "Tier 1 Preferred",
    destinationWarehouseId: "wh-2",
    destinationWarehouseName: "Hub Surabaya",
    status: "ISSUED",
    orderDate: "2026-08-05",
    expectedDeliveryDate: "2026-08-18",
    totalCost: 4200,
    lineItems: [
      {
        id: "li-3",
        productId: "prod-3",
        productName: "Logitech MX Master 3S",
        sku: "MOU-LOG-MX3S",
        orderedQuantity: 30,
        receivedQuantity: 0,
        unitCost: 90,
      },
      {
        id: "li-4",
        productId: "prod-4",
        productName: "Keychron K2 Mechanical Keyboard",
        sku: "KEY-KCH-K2",
        orderedQuantity: 15,
        receivedQuantity: 0,
        unitCost: 100,
      },
    ],
    receipts: [],
    notes: "Standard monthly restock for Surabaya hub.",
  },
  {
    id: "po-103",
    poNumber: "PO-2026-003",
    supplierId: "sup-3",
    supplierName: "Samsung Semiconductor Asia",
    supplierTier: "Tier 2 Standard",
    destinationWarehouseId: "wh-1",
    destinationWarehouseName: "Gudang Utama Jakarta",
    status: "RECEIVED",
    orderDate: "2026-07-20",
    expectedDeliveryDate: "2026-08-02",
    totalCost: 12000,
    lineItems: [
      {
        id: "li-5",
        productId: "prod-5",
        productName: "Samsung 990 Pro 2TB NVMe SSD",
        sku: "SSD-SAM-990P-2T",
        orderedQuantity: 60,
        receivedQuantity: 60,
        unitCost: 200,
      },
    ],
    receipts: [
      {
        id: "rc-2",
        poId: "po-103",
        receivedAt: "2026-08-01 14:15",
        warehouseId: "wh-1",
        warehouseName: "Gudang Utama Jakarta",
        items: [
          { sku: "SSD-SAM-990P-2T", productName: "Samsung 990 Pro 2TB NVMe SSD", quantityReceived: 60 },
        ],
        notes: "Full delivery inspected and stored in Zone A3.",
      },
    ],
    notes: "Quarterly flash storage batch.",
  },
  {
    id: "po-104",
    poNumber: "PO-2026-004",
    supplierId: "sup-4",
    supplierName: "ASUS Tek Procurement",
    supplierTier: "Tier 2 Standard",
    destinationWarehouseId: "wh-3",
    destinationWarehouseName: "Depot Medan",
    status: "DRAFT",
    orderDate: "2026-08-12",
    expectedDeliveryDate: "2026-08-25",
    totalCost: 6500,
    lineItems: [
      {
        id: "li-6",
        productId: "prod-6",
        productName: "ASUS ROG Swift 27-inch Monitor",
        sku: "MON-ASU-ROG27",
        orderedQuantity: 10,
        receivedQuantity: 0,
        unitCost: 650,
      },
    ],
    receipts: [],
    notes: "Draft order for Q3 gaming monitor restock.",
  },
];
