import type {
  WarehouseItem,
  WarehouseType,
  WarehouseStatus,
  WarehouseZone,
  StoredInventorySummary,
  WarehouseTransferLog,
} from "./types";

export const WAREHOUSE_TYPES: { label: string; value: WarehouseType }[] = [
  { label: "Central Hub", value: "central_hub" },
  { label: "Regional Depot", value: "regional_depot" },
  { label: "Cold Storage & Lab", value: "cold_storage" },
  { label: "Fulfillment Center", value: "fulfillment" },
  { label: "Transit Hub", value: "transit" },
];

export const WAREHOUSE_STATUSES: { label: string; value: WarehouseStatus }[] = [
  { label: "Active", value: "active" },
  { label: "Under Maintenance", value: "maintenance" },
  { label: "Near Full", value: "full" },
  { label: "Inactive", value: "inactive" },
];

export const MOCK_GLOBAL_TRANSFER_LOGS: WarehouseTransferLog[] = [
  {
    id: "trf-001",
    reference: "TRF-2026-001",
    sourceWarehouseId: "wh-1",
    sourceWarehouseName: "Main Hub (WH-1)",
    destinationWarehouseId: "wh-2",
    destinationWarehouseName: "East Annex (WH-2)",
    sku: "ELEC-MCU-001",
    itemName: "STM32F401 Microcontroller Board",
    quantity: 25,
    dispatchedBy: "Alex Morgan",
    timestamp: "2026-08-12 10:15",
    status: "completed",
    notes: "Urgent replenishment for East Java robotics batch run.",
  },
  {
    id: "trf-002",
    reference: "TRF-2026-002",
    sourceWarehouseId: "wh-1",
    sourceWarehouseName: "Main Hub (WH-1)",
    destinationWarehouseId: "wh-3",
    destinationWarehouseName: "Central Depot (WH-3)",
    sku: "MECH-MOT-002",
    itemName: "NEMA 17 Stepper Motor 1.8°",
    quantity: 15,
    dispatchedBy: "Sarah Chen",
    timestamp: "2026-08-11 16:45",
    status: "completed",
    notes: "Stock rebalance for 3D printer assembly line.",
  },
  {
    id: "trf-003",
    reference: "TRF-2026-003",
    sourceWarehouseId: "wh-3",
    sourceWarehouseName: "Central Depot (WH-3)",
    destinationWarehouseId: "wh-5",
    destinationWarehouseName: "Transit Logistics Hub (WH-5)",
    sku: "STR-ALU-020",
    itemName: "2020 V-Slot Aluminum Extrusion 1000mm",
    quantity: 40,
    dispatchedBy: "Budi Santoso",
    timestamp: "2026-08-10 14:20",
    status: "completed",
    notes: "Staging materials for project site delivery.",
  },
  {
    id: "trf-004",
    reference: "TRF-2026-004",
    sourceWarehouseId: "wh-2",
    sourceWarehouseName: "East Annex (WH-2)",
    destinationWarehouseId: "wh-4",
    destinationWarehouseName: "Cold Storage & Lab (WH-4)",
    sku: "ELEC-SEN-004",
    itemName: "DHT22 Temperature & Humidity Sensor",
    quantity: 10,
    dispatchedBy: "Dave Miller",
    timestamp: "2026-08-09 11:30",
    status: "completed",
    notes: "Environmental chamber calibration testing stock.",
  },
];

export const MOCK_WAREHOUSES: WarehouseItem[] = [
  {
    id: "wh-1",
    code: "WH-01",
    name: "Main Hub (WH-1)",
    type: "central_hub",
    status: "active",
    address: {
      street: "Jl. Industri Raya No. 45, Daan Mogot",
      city: "Jakarta Barat",
      province: "DKI Jakarta",
      postalCode: "11840",
    },
    manager: {
      name: "Alex Morgan",
      email: "alex.morgan@stockos.internal",
      phone: "+62 811-9234-5678",
    },
    totalCapacityUnits: 6000,
    usedCapacityUnits: 4450,
    totalSkusCount: 18,
    totalValuation: 284500000,
    zones: [
      {
        id: "zn-1-a",
        code: "ZN-A",
        name: "Zone A - Microcontrollers & ICs",
        type: "shelf",
        capacityUnits: 1500,
        usedUnits: 1200,
      },
      {
        id: "zn-1-b",
        code: "ZN-B",
        name: "Zone B - Motors & Actuators",
        type: "rack",
        capacityUnits: 2000,
        usedUnits: 1550,
      },
      {
        id: "zn-1-c",
        code: "ZN-C",
        name: "Zone C - Structural Extrusions & Bulk",
        type: "bulk",
        capacityUnits: 2000,
        usedUnits: 1400,
      },
      {
        id: "zn-1-d",
        code: "ZN-D",
        name: "Zone D - Rapid Dispatch Staging",
        type: "shelf",
        capacityUnits: 500,
        usedUnits: 300,
      },
    ],
    storedInventory: [
      {
        id: "inv-001",
        sku: "ELEC-MCU-001",
        name: "STM32F401 Microcontroller Board",
        category: "Electronics",
        quantity: 120,
        available: 110,
        unitCost: 185000,
        unit: "pcs",
        locationBin: "A-01-12",
      },
      {
        id: "inv-002",
        sku: "ELEC-SEN-004",
        name: "DHT22 Temperature & Humidity Sensor",
        category: "Sensors",
        quantity: 85,
        available: 75,
        unitCost: 42000,
        unit: "pcs",
        locationBin: "A-02-04",
      },
      {
        id: "inv-003",
        sku: "MECH-MOT-002",
        name: "NEMA 17 Stepper Motor 1.8°",
        category: "Motors",
        quantity: 140,
        available: 125,
        unitCost: 125000,
        unit: "pcs",
        locationBin: "B-03-08",
      },
      {
        id: "inv-004",
        sku: "STR-ALU-020",
        name: "2020 V-Slot Aluminum Extrusion 1000mm",
        category: "Structural",
        quantity: 210,
        available: 195,
        unitCost: 68000,
        unit: "pcs",
        locationBin: "C-01-01",
      },
      {
        id: "inv-005",
        sku: "PWR-PSU-350",
        name: "Mean Well LRS-350-24 Power Supply",
        category: "Power",
        quantity: 65,
        available: 60,
        unitCost: 380000,
        unit: "pcs",
        locationBin: "B-02-14",
      },
    ],
    transferLogs: [MOCK_GLOBAL_TRANSFER_LOGS[0], MOCK_GLOBAL_TRANSFER_LOGS[1]],
    createdAt: "2026-01-10",
  },
  {
    id: "wh-2",
    code: "WH-02",
    name: "East Annex (WH-2)",
    type: "regional_depot",
    status: "active",
    address: {
      street: "Kawasan Industri Rungkut Megah Blok B-12",
      city: "Surabaya",
      province: "Jawa Timur",
      postalCode: "60293",
    },
    manager: {
      name: "Sarah Chen",
      email: "sarah.chen@stockos.internal",
      phone: "+62 812-8877-6655",
    },
    totalCapacityUnits: 4500,
    usedCapacityUnits: 2980,
    totalSkusCount: 12,
    totalValuation: 168200000,
    zones: [
      {
        id: "zn-2-a",
        code: "ZN-A",
        name: "Zone A - Regional Distribution Shelves",
        type: "shelf",
        capacityUnits: 1500,
        usedUnits: 980,
      },
      {
        id: "zn-2-b",
        code: "ZN-B",
        name: "Zone B - Pallet Racks & Heavy Spares",
        type: "rack",
        capacityUnits: 2000,
        usedUnits: 1450,
      },
      {
        id: "zn-2-c",
        code: "ZN-C",
        name: "Zone C - Outbound Dispatch Lane",
        type: "bulk",
        capacityUnits: 1000,
        usedUnits: 550,
      },
    ],
    storedInventory: [
      {
        id: "inv-006",
        sku: "ELEC-MCU-001",
        name: "STM32F401 Microcontroller Board",
        category: "Electronics",
        quantity: 45,
        available: 40,
        unitCost: 185000,
        unit: "pcs",
        locationBin: "A-01-08",
      },
      {
        id: "inv-007",
        sku: "MECH-MOT-002",
        name: "NEMA 17 Stepper Motor 1.8°",
        category: "Motors",
        quantity: 60,
        available: 55,
        unitCost: 125000,
        unit: "pcs",
        locationBin: "B-02-01",
      },
      {
        id: "inv-008",
        sku: "STR-ALU-020",
        name: "2020 V-Slot Aluminum Extrusion 1000mm",
        category: "Structural",
        quantity: 95,
        available: 90,
        unitCost: 68000,
        unit: "pcs",
        locationBin: "C-01-04",
      },
    ],
    transferLogs: [MOCK_GLOBAL_TRANSFER_LOGS[0], MOCK_GLOBAL_TRANSFER_LOGS[3]],
    createdAt: "2026-02-15",
  },
  {
    id: "wh-3",
    code: "WH-03",
    name: "Central Depot (WH-3)",
    type: "fulfillment",
    status: "active",
    address: {
      street: "Jl. Soekarno-Hatta No. 582, Gedebage",
      city: "Bandung",
      province: "Jawa Barat",
      postalCode: "40294",
    },
    manager: {
      name: "Dave Miller",
      email: "dave.miller@stockos.internal",
      phone: "+62 813-1122-3344",
    },
    totalCapacityUnits: 5000,
    usedCapacityUnits: 4120,
    totalSkusCount: 15,
    totalValuation: 215800000,
    zones: [
      {
        id: "zn-3-a",
        code: "ZN-A",
        name: "Zone A - High-Speed Pick & Pack Shelving",
        type: "shelf",
        capacityUnits: 2000,
        usedUnits: 1750,
      },
      {
        id: "zn-3-b",
        code: "ZN-B",
        name: "Zone B - Main Storage Racks",
        type: "rack",
        capacityUnits: 2500,
        usedUnits: 2050,
      },
      {
        id: "zn-3-c",
        code: "ZN-C",
        name: "Zone C - Returns Inspection Bay",
        type: "bulk",
        capacityUnits: 500,
        usedUnits: 320,
      },
    ],
    storedInventory: [
      {
        id: "inv-009",
        sku: "ELEC-SEN-004",
        name: "DHT22 Temperature & Humidity Sensor",
        category: "Sensors",
        quantity: 50,
        available: 48,
        unitCost: 42000,
        unit: "pcs",
        locationBin: "A-01-02",
      },
      {
        id: "inv-010",
        sku: "PWR-PSU-350",
        name: "Mean Well LRS-350-24 Power Supply",
        category: "Power",
        quantity: 40,
        available: 35,
        unitCost: 380000,
        unit: "pcs",
        locationBin: "B-01-11",
      },
      {
        id: "inv-011",
        sku: "STR-ALU-020",
        name: "2020 V-Slot Aluminum Extrusion 1000mm",
        category: "Structural",
        quantity: 110,
        available: 100,
        unitCost: 68000,
        unit: "pcs",
        locationBin: "B-03-02",
      },
    ],
    transferLogs: [MOCK_GLOBAL_TRANSFER_LOGS[1], MOCK_GLOBAL_TRANSFER_LOGS[2]],
    createdAt: "2026-03-01",
  },
  {
    id: "wh-4",
    code: "WH-04",
    name: "Cold Storage & Lab (WH-4)",
    type: "cold_storage",
    status: "maintenance",
    address: {
      street: "Kawasan Pergudangan Taman Tekno Blok F No. 8",
      city: "Tangerang Selatan",
      province: "Banten",
      postalCode: "15314",
    },
    manager: {
      name: "Dr. Maya Lin",
      email: "maya.lin@stockos.internal",
      phone: "+62 817-4455-6677",
    },
    totalCapacityUnits: 2000,
    usedCapacityUnits: 650,
    totalSkusCount: 6,
    totalValuation: 95400000,
    zones: [
      {
        id: "zn-4-a",
        code: "ZN-A",
        name: "Zone A - Climate Controlled Cold Room (-5°C to 4°C)",
        type: "cold_room",
        capacityUnits: 1200,
        usedUnits: 400,
      },
      {
        id: "zn-4-b",
        code: "ZN-B",
        name: "Zone B - Precision Lab Calibration Racks",
        type: "rack",
        capacityUnits: 800,
        usedUnits: 250,
      },
    ],
    storedInventory: [
      {
        id: "inv-012",
        sku: "ELEC-SEN-004",
        name: "DHT22 Temperature & Humidity Sensor",
        category: "Sensors",
        quantity: 25,
        available: 20,
        unitCost: 42000,
        unit: "pcs",
        locationBin: "CR-01-03",
      },
      {
        id: "inv-013",
        sku: "ELEC-MCU-001",
        name: "STM32F401 Microcontroller Board",
        category: "Electronics",
        quantity: 30,
        available: 30,
        unitCost: 185000,
        unit: "pcs",
        locationBin: "LB-02-01",
      },
    ],
    transferLogs: [MOCK_GLOBAL_TRANSFER_LOGS[3]],
    createdAt: "2026-04-18",
  },
  {
    id: "wh-5",
    code: "WH-05",
    name: "Transit Logistics Hub (WH-5)",
    type: "transit",
    status: "active",
    address: {
      street: "Jl. Diponegoro KM 38, Tambun Selatan",
      city: "Bekasi",
      province: "Jawa Barat",
      postalCode: "17510",
    },
    manager: {
      name: "Budi Santoso",
      email: "budi.santoso@stockos.internal",
      phone: "+62 819-7788-9900",
    },
    totalCapacityUnits: 3500,
    usedCapacityUnits: 2650,
    totalSkusCount: 8,
    totalValuation: 142000000,
    zones: [
      {
        id: "zn-5-a",
        code: "ZN-A",
        name: "Zone A - Cross-Docking Staging Bay",
        type: "bulk",
        capacityUnits: 2000,
        usedUnits: 1600,
      },
      {
        id: "zn-5-b",
        code: "ZN-B",
        name: "Zone B - Rapid Transit Fast-Flow Aisle",
        type: "shelf",
        capacityUnits: 1500,
        usedUnits: 1050,
      },
    ],
    storedInventory: [
      {
        id: "inv-014",
        sku: "STR-ALU-020",
        name: "2020 V-Slot Aluminum Extrusion 1000mm",
        category: "Structural",
        quantity: 80,
        available: 80,
        unitCost: 68000,
        unit: "pcs",
        locationBin: "CD-01-09",
      },
      {
        id: "inv-015",
        sku: "PWR-PSU-350",
        name: "Mean Well LRS-350-24 Power Supply",
        category: "Power",
        quantity: 35,
        available: 30,
        unitCost: 380000,
        unit: "pcs",
        locationBin: "TF-02-04",
      },
    ],
    transferLogs: [MOCK_GLOBAL_TRANSFER_LOGS[2]],
    createdAt: "2026-05-20",
  },
];
