import type {
  ValuationSummary,
  MovementVelocityItem,
  ReorderRiskItem,
  WarehousePerformance,
  SupplierPerformance,
  MovementTrendPoint,
} from "./types";

export const MOCK_VALUATION_SUMMARY: ValuationSummary = {
  totalValuation: 142850.0,
  totalCost: 89400.0,
  grossMargin: 53450.0,
  marginPercent: 37.4,
  totalSKUs: 124,
  categories: [
    {
      categoryId: "cat-elec",
      categoryName: "Electronics & Sensors",
      itemCount: 38,
      stockQty: 1420,
      totalCost: 45200.0,
      totalRetailValue: 74500.0,
      marginPercent: 39.3,
      ratioPercent: 52.1,
    },
    {
      categoryId: "cat-tools",
      categoryName: "Industrial Tools",
      itemCount: 42,
      stockQty: 890,
      totalCost: 24100.0,
      totalRetailValue: 36800.0,
      marginPercent: 34.5,
      ratioPercent: 25.8,
    },
    {
      categoryId: "cat-raw",
      categoryName: "Raw Materials",
      itemCount: 22,
      stockQty: 3400,
      totalCost: 12400.0,
      totalRetailValue: 18900.0,
      marginPercent: 34.4,
      ratioPercent: 13.2,
    },
    {
      categoryId: "cat-pack",
      categoryName: "Packaging Materials",
      itemCount: 14,
      stockQty: 6200,
      totalCost: 5200.0,
      totalRetailValue: 8450.0,
      marginPercent: 38.5,
      ratioPercent: 5.9,
    },
    {
      categoryId: "cat-apparel",
      categoryName: "Safety Gear & Apparel",
      itemCount: 8,
      stockQty: 410,
      totalCost: 2500.0,
      totalRetailValue: 4200.0,
      marginPercent: 40.5,
      ratioPercent: 3.0,
    },
  ],
};

export const MOCK_MOVEMENT_VELOCITY: MovementVelocityItem[] = [
  {
    productId: "prod-001",
    sku: "EL-SENS-09",
    name: "Precision Pressure Transducer 500PSI",
    category: "Electronics & Sensors",
    warehouse: "Main Logistics Hub",
    stockInQty: 450,
    stockOutQty: 390,
    currentStock: 120,
    turnoverRatio: 5.8,
    velocityTier: "fast",
    lastMovementDate: "2026-08-12",
  },
  {
    productId: "prod-002",
    sku: "TL-WREN-14",
    name: "Heavy Duty Pneumatic Impact Wrench 1/2\"",
    category: "Industrial Tools",
    warehouse: "West Coast Annex",
    stockInQty: 180,
    stockOutQty: 165,
    currentStock: 45,
    turnoverRatio: 4.2,
    velocityTier: "fast",
    lastMovementDate: "2026-08-11",
  },
  {
    productId: "prod-003",
    sku: "RM-ALUM-60",
    name: "Aluminum T6 Extrusion Bar 6061 2m",
    category: "Raw Materials",
    warehouse: "North Storage Depot",
    stockInQty: 600,
    stockOutQty: 520,
    currentStock: 310,
    turnoverRatio: 3.5,
    velocityTier: "moderate",
    lastMovementDate: "2026-08-10",
  },
  {
    productId: "prod-004",
    sku: "PK-BOX-02",
    name: "Heavy-Duty Corrugated Box 40x40x40cm",
    category: "Packaging Materials",
    warehouse: "Main Logistics Hub",
    stockInQty: 2500,
    stockOutQty: 2100,
    currentStock: 1400,
    turnoverRatio: 3.1,
    velocityTier: "moderate",
    lastMovementDate: "2026-08-12",
  },
  {
    productId: "prod-005",
    sku: "SG-GLOV-08",
    name: "Kevlar Heat-Resistant Gloves L",
    category: "Safety Gear & Apparel",
    warehouse: "North Storage Depot",
    stockInQty: 120,
    stockOutQty: 45,
    currentStock: 95,
    turnoverRatio: 1.2,
    velocityTier: "slow",
    lastMovementDate: "2026-08-04",
  },
  {
    productId: "prod-006",
    sku: "EL-CABL-03",
    name: "Industrial Armored Cable 4-Core 50m",
    category: "Electronics & Sensors",
    warehouse: "West Coast Annex",
    stockInQty: 30,
    stockOutQty: 4,
    currentStock: 85,
    turnoverRatio: 0.2,
    velocityTier: "dead",
    lastMovementDate: "2026-06-15",
  },
  {
    productId: "prod-007",
    sku: "TL-DRILL-9",
    name: "Titanium Carbide Drill Bit Set 12-Piece",
    category: "Industrial Tools",
    warehouse: "Main Logistics Hub",
    stockInQty: 210,
    stockOutQty: 195,
    currentStock: 38,
    turnoverRatio: 4.9,
    velocityTier: "fast",
    lastMovementDate: "2026-08-12",
  },
  {
    productId: "prod-008",
    sku: "RM-COP-10",
    name: "Copper Grounding Busbar 300mm",
    category: "Raw Materials",
    warehouse: "North Storage Depot",
    stockInQty: 40,
    stockOutQty: 2,
    currentStock: 110,
    turnoverRatio: 0.1,
    velocityTier: "dead",
    lastMovementDate: "2026-05-20",
  },
];

export const MOCK_REORDER_RISK: ReorderRiskItem[] = [
  {
    productId: "prod-001",
    sku: "EL-SENS-09",
    name: "Precision Pressure Transducer 500PSI",
    category: "Electronics & Sensors",
    warehouse: "Main Logistics Hub",
    currentStock: 12,
    minThreshold: 50,
    daysRemaining: 2,
    suggestedReorderQty: 100,
    unitCost: 185.0,
    totalReorderCost: 18500.0,
    urgency: "critical",
    leadTimeDays: 5,
    supplierName: "Apex Microelectronics Inc.",
  },
  {
    productId: "prod-007",
    sku: "TL-DRILL-9",
    name: "Titanium Carbide Drill Bit Set 12-Piece",
    category: "Industrial Tools",
    warehouse: "Main Logistics Hub",
    currentStock: 8,
    minThreshold: 30,
    daysRemaining: 3,
    suggestedReorderQty: 50,
    unitCost: 65.0,
    totalReorderCost: 3250.0,
    urgency: "critical",
    leadTimeDays: 4,
    supplierName: "Vanguard Industrial Supply Co.",
  },
  {
    productId: "prod-002",
    sku: "TL-WREN-14",
    name: "Heavy Duty Pneumatic Impact Wrench 1/2\"",
    category: "Industrial Tools",
    warehouse: "West Coast Annex",
    currentStock: 18,
    minThreshold: 40,
    daysRemaining: 6,
    suggestedReorderQty: 40,
    unitCost: 145.0,
    totalReorderCost: 5800.0,
    urgency: "warning",
    leadTimeDays: 7,
    supplierName: "Vanguard Industrial Supply Co.",
  },
  {
    productId: "prod-003",
    sku: "RM-ALUM-60",
    name: "Aluminum T6 Extrusion Bar 6061 2m",
    category: "Raw Materials",
    warehouse: "North Storage Depot",
    currentStock: 45,
    minThreshold: 80,
    daysRemaining: 9,
    suggestedReorderQty: 150,
    unitCost: 28.0,
    totalReorderCost: 4200.0,
    urgency: "warning",
    leadTimeDays: 10,
    supplierName: "Titan Metals Fabrication",
  },
  {
    productId: "prod-004",
    sku: "PK-BOX-02",
    name: "Heavy-Duty Corrugated Box 40x40x40cm",
    category: "Packaging Materials",
    warehouse: "Main Logistics Hub",
    currentStock: 420,
    minThreshold: 500,
    daysRemaining: 12,
    suggestedReorderQty: 1000,
    unitCost: 1.25,
    totalReorderCost: 1250.0,
    urgency: "warning",
    leadTimeDays: 3,
    supplierName: "EcoPack Containers Ltd.",
  },
  {
    productId: "prod-005",
    sku: "SG-GLOV-08",
    name: "Kevlar Heat-Resistant Gloves L",
    category: "Safety Gear & Apparel",
    warehouse: "North Storage Depot",
    currentStock: 95,
    minThreshold: 50,
    daysRemaining: 28,
    suggestedReorderQty: 50,
    unitCost: 22.0,
    totalReorderCost: 1100.0,
    urgency: "optimal",
    leadTimeDays: 5,
    supplierName: "ShieldTek Safety Gear",
  },
];

export const MOCK_WAREHOUSE_PERFORMANCE: WarehousePerformance[] = [
  {
    warehouseId: "wh-01",
    name: "Main Logistics Hub",
    code: "WH-MAIN-01",
    location: "Chicago, IL - Sector A",
    capacityUsedPercent: 88.5,
    totalValuation: 84500.0,
    stockCount: 5420,
    turnoverRate: 4.8,
    status: "near_capacity",
  },
  {
    warehouseId: "wh-02",
    name: "West Coast Annex",
    code: "WH-WEST-02",
    location: "Reno, NV - Zone 4",
    capacityUsedPercent: 64.2,
    totalValuation: 38200.0,
    stockCount: 2150,
    turnoverRate: 3.9,
    status: "optimal",
  },
  {
    warehouseId: "wh-03",
    name: "North Storage Depot",
    code: "WH-NTH-03",
    location: "Minneapolis, MN - Bay 12",
    capacityUsedPercent: 41.0,
    totalValuation: 20150.0,
    stockCount: 1680,
    turnoverRate: 2.1,
    status: "underutilized",
  },
];

export const MOCK_SUPPLIER_PERFORMANCE: SupplierPerformance[] = [
  {
    supplierId: "sup-01",
    name: "Apex Microelectronics Inc.",
    code: "SUP-APEX",
    fulfilledOrders: 142,
    onTimeDeliveryRate: 98.2,
    qualityRating: 4.9,
    totalSpend: 112400.0,
    status: "preferred",
  },
  {
    supplierId: "sup-02",
    name: "Vanguard Industrial Supply Co.",
    code: "SUP-VANGUARD",
    fulfilledOrders: 89,
    onTimeDeliveryRate: 95.4,
    qualityRating: 4.7,
    totalSpend: 68500.0,
    status: "preferred",
  },
  {
    supplierId: "sup-03",
    name: "Titan Metals Fabrication",
    code: "SUP-TITAN",
    fulfilledOrders: 44,
    onTimeDeliveryRate: 91.0,
    qualityRating: 4.4,
    totalSpend: 42100.0,
    status: "active",
  },
  {
    supplierId: "sup-04",
    name: "EcoPack Containers Ltd.",
    code: "SUP-ECOPACK",
    fulfilledOrders: 76,
    onTimeDeliveryRate: 99.1,
    qualityRating: 4.8,
    totalSpend: 18400.0,
    status: "preferred",
  },
  {
    supplierId: "sup-05",
    name: "ShieldTek Safety Gear",
    code: "SUP-SHIELD",
    fulfilledOrders: 18,
    onTimeDeliveryRate: 82.5,
    qualityRating: 3.9,
    totalSpend: 9200.0,
    status: "under_review",
  },
];

export const MOCK_MOVEMENT_TRENDS_30D: MovementTrendPoint[] = [
  { date: "Jul 15", stockIn: 120, stockOut: 95, netFlow: 25 },
  { date: "Jul 18", stockIn: 80, stockOut: 140, netFlow: -60 },
  { date: "Jul 21", stockIn: 320, stockOut: 180, netFlow: 140 },
  { date: "Jul 24", stockIn: 150, stockOut: 210, netFlow: -60 },
  { date: "Jul 27", stockIn: 450, stockOut: 290, netFlow: 160 },
  { date: "Jul 30", stockIn: 210, stockOut: 190, netFlow: 20 },
  { date: "Aug 02", stockIn: 380, stockOut: 310, netFlow: 70 },
  { date: "Aug 05", stockIn: 290, stockOut: 340, netFlow: -50 },
  { date: "Aug 08", stockIn: 540, stockOut: 420, netFlow: 120 },
  { date: "Aug 11", stockIn: 410, stockOut: 380, netFlow: 30 },
  { date: "Aug 13", stockIn: 180, stockOut: 230, netFlow: -50 },
];
