import type { Product, ProductCategory } from "./types";

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "Electronics",
  "Mechanical",
  "Structural",
  "Motors",
  "Power",
  "Consumables",
  "Cables & Adapters",
  "3D Printing",
  "Fasteners",
  "Tools",
  "Sensors",
];

export const PRODUCT_UNITS = [
  "pcs",
  "units",
  "kits",
  "sets",
  "spools",
  "bars",
  "cells",
  "tubes",
  "kg",
  "m",
];

export const WAREHOUSES = [
  "Main Hub (WH-1)",
  "East Annex (WH-2)",
  "Central Depot (WH-3)",
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "ELEC-ESP-32",
    name: "ESP32-WROOM-32D Microcontroller Module",
    category: "Electronics",
    currentStock: 0,
    minStock: 50,
    unit: "pcs",
    unitPrice: 4.85,
    warehouse: "Main Hub (WH-1)",
    status: "out_of_stock",
    barcode: "890123450001",
    supplier: "Espressif Systems Ltd.",
    description: "Dual-core 240MHz Wi-Fi and Bluetooth MCU module with integrated antenna.",
    lastRestocked: "14 days ago",
    createdAt: "2026-01-15",
    movementLogs: [
      {
        id: "log-101",
        type: "out",
        quantity: 50,
        reference: "SO-2026-089",
        timestamp: "2026-02-10 14:30",
        performedBy: "Alex Morgan",
        note: "Production batch dispatch for IoT Gateway project.",
      },
      {
        id: "log-102",
        type: "in",
        quantity: 100,
        reference: "PO-2026-012",
        timestamp: "2026-01-29 09:15",
        performedBy: "Sarah Chen",
        note: "Inbound supplier delivery.",
      },
    ],
  },
  {
    id: "prod-2",
    sku: "MECH-BRG-608",
    name: "Industrial Ball Bearing 608RS (8x22x7mm)",
    category: "Mechanical",
    currentStock: 0,
    minStock: 100,
    unit: "pcs",
    unitPrice: 1.25,
    warehouse: "East Annex (WH-2)",
    status: "out_of_stock",
    barcode: "890123450002",
    supplier: "Precision Motion Components",
    description: "Rubber sealed deep groove carbon steel ball bearing for robotics & 3D printers.",
    lastRestocked: "21 days ago",
    createdAt: "2026-01-10",
    movementLogs: [
      {
        id: "log-103",
        type: "out",
        quantity: 120,
        reference: "SO-2026-074",
        timestamp: "2026-02-01 11:20",
        performedBy: "Alex Morgan",
        note: "Assembly line batch requirement.",
      },
    ],
  },
  {
    id: "prod-3",
    sku: "ALUM-EXT-2020",
    name: "T-Slot Aluminum Extrusion 2020 (1000mm)",
    category: "Structural",
    currentStock: 0,
    minStock: 30,
    unit: "bars",
    unitPrice: 8.9,
    warehouse: "Main Hub (WH-1)",
    status: "out_of_stock",
    barcode: "890123450003",
    supplier: "AluProfile Industrial",
    description: "Anodized black aluminum V-slot extrusion profile for framing and CNC linear motion.",
    lastRestocked: "18 days ago",
    createdAt: "2026-01-08",
    movementLogs: [
      {
        id: "log-104",
        type: "out",
        quantity: 35,
        reference: "SO-2026-061",
        timestamp: "2026-02-04 16:45",
        performedBy: "Sarah Chen",
        note: "Rig structural frame build.",
      },
    ],
  },
  {
    id: "prod-4",
    sku: "MOTR-STP-17",
    name: "NEMA 17 Stepper Motor 42BYGH",
    category: "Motors",
    currentStock: 4,
    minStock: 25,
    unit: "units",
    unitPrice: 14.5,
    warehouse: "Main Hub (WH-1)",
    status: "low_stock",
    barcode: "890123450004",
    supplier: "StepTorque Electric",
    description: "1.8 deg high torque hybrid stepper motor 1.5A 4-lead with cable.",
    lastRestocked: "8 days ago",
    createdAt: "2026-01-12",
    movementLogs: [
      {
        id: "log-105",
        type: "out",
        quantity: 16,
        reference: "SO-2026-092",
        timestamp: "2026-02-11 10:00",
        performedBy: "Alex Morgan",
        note: "CNC multi-axis drive upgrade.",
      },
    ],
  },
  {
    id: "prod-5",
    sku: "BATT-LION-1865",
    name: "Rechargeable Li-ion Cell 18650 3.7V 3000mAh",
    category: "Power",
    currentStock: 12,
    minStock: 80,
    unit: "cells",
    unitPrice: 5.4,
    warehouse: "East Annex (WH-2)",
    status: "low_stock",
    barcode: "890123450005",
    supplier: "VoltMax Energy Corp",
    description: "High discharge 20A continuous flat top lithium-ion battery cell.",
    lastRestocked: "5 days ago",
    createdAt: "2026-01-14",
    movementLogs: [
      {
        id: "log-106",
        type: "out",
        quantity: 40,
        reference: "SO-2026-099",
        timestamp: "2026-02-12 08:30",
        performedBy: "Sarah Chen",
        note: "Portable battery pack manufacturing.",
      },
    ],
  },
  {
    id: "prod-6",
    sku: "THRM-PST-5G",
    name: "High-Performance Thermal Paste 5g Syringe",
    category: "Consumables",
    currentStock: 8,
    minStock: 40,
    unit: "tubes",
    unitPrice: 6.75,
    warehouse: "Main Hub (WH-1)",
    status: "low_stock",
    barcode: "890123450006",
    supplier: "ThermalCraft Lab",
    description: "Micro-carbon thermal compound 8.5 W/mK for CPU/GPU heat sinks.",
    lastRestocked: "3 days ago",
    createdAt: "2026-01-18",
    movementLogs: [
      {
        id: "log-107",
        type: "out",
        quantity: 20,
        reference: "SO-2026-102",
        timestamp: "2026-02-12 13:10",
        performedBy: "Alex Morgan",
        note: "Service maintenance maintenance consumption.",
      },
    ],
  },
  {
    id: "prod-7",
    sku: "CABL-USBC-2M",
    name: "Braided USB-C to USB-C Cable 100W 2m",
    category: "Cables & Adapters",
    currentStock: 240,
    minStock: 50,
    unit: "pcs",
    unitPrice: 7.2,
    warehouse: "Central Depot (WH-3)",
    status: "in_stock",
    barcode: "890123450007",
    supplier: "ConnectPro Global",
    description: "Nylon braided heavy-duty E-mark chip PD 3.0 100W fast charging cable.",
    lastRestocked: "2 days ago",
    createdAt: "2026-01-05",
    movementLogs: [
      {
        id: "log-108",
        type: "in",
        quantity: 300,
        reference: "PO-2026-033",
        timestamp: "2026-02-10 10:45",
        performedBy: "Sarah Chen",
        note: "Bulk restock received from distributor.",
      },
      {
        id: "log-109",
        type: "out",
        quantity: 60,
        reference: "SO-2026-105",
        timestamp: "2026-02-11 15:00",
        performedBy: "Alex Morgan",
        note: "Retail store packaging order.",
      },
    ],
  },
  {
    id: "prod-8",
    sku: "FILA-PLA-BLK",
    name: "PLA+ 3D Printer Filament 1.75mm Black 1kg",
    category: "3D Printing",
    currentStock: 180,
    minStock: 40,
    unit: "spools",
    unitPrice: 19.5,
    warehouse: "Main Hub (WH-1)",
    status: "in_stock",
    barcode: "890123450008",
    supplier: "PolyForm Polymers",
    description: "Enhanced toughness biodegradable PLA+ filament, vacuum sealed with desiccant.",
    lastRestocked: "4 days ago",
    createdAt: "2026-01-07",
    movementLogs: [
      {
        id: "log-110",
        type: "in",
        quantity: 250,
        reference: "PO-2026-028",
        timestamp: "2026-02-08 11:30",
        performedBy: "Sarah Chen",
        note: "Shipment from manufacturing facility.",
      },
    ],
  },
  {
    id: "prod-9",
    sku: "FAST-M3-SS",
    name: "M3 Stainless Steel Socket Head Screw Kit (500pcs)",
    category: "Fasteners",
    currentStock: 95,
    minStock: 30,
    unit: "kits",
    unitPrice: 16.8,
    warehouse: "East Annex (WH-2)",
    status: "in_stock",
    barcode: "890123450009",
    supplier: "FastenerHub Ltd",
    description: "304 stainless steel M3 x 6/8/10/12/16/20mm hex socket cap screws with nuts and washers.",
    lastRestocked: "6 days ago",
    createdAt: "2026-01-11",
    movementLogs: [
      {
        id: "log-111",
        type: "in",
        quantity: 100,
        reference: "PO-2026-025",
        timestamp: "2026-02-06 14:00",
        performedBy: "Alex Morgan",
        note: "Fastener replenishment.",
      },
    ],
  },
  {
    id: "prod-10",
    sku: "TOOL-PRC-24",
    name: "Precision Magnetic Screwdriver Set (24 Bits)",
    category: "Tools",
    currentStock: 74,
    minStock: 20,
    unit: "sets",
    unitPrice: 22.0,
    warehouse: "Main Hub (WH-1)",
    status: "in_stock",
    barcode: "890123450010",
    supplier: "WerkTool Instruments",
    description: "S2 steel alloy magnetic driver kit in aluminum alloy storage case for electronics repair.",
    lastRestocked: "9 days ago",
    createdAt: "2026-01-09",
    movementLogs: [
      {
        id: "log-112",
        type: "in",
        quantity: 80,
        reference: "PO-2026-018",
        timestamp: "2026-02-03 09:40",
        performedBy: "Sarah Chen",
        note: "New toolset consignment.",
      },
    ],
  },
  {
    id: "prod-11",
    sku: "SENS-ENV-BME",
    name: "BME280 Temperature Humidity Sensor Module",
    category: "Sensors",
    currentStock: 115,
    minStock: 35,
    unit: "pcs",
    unitPrice: 3.95,
    warehouse: "Main Hub (WH-1)",
    status: "in_stock",
    barcode: "890123450011",
    supplier: "SensorTech Micro",
    description: "Digital sensor measuring relative humidity, barometric pressure and ambient temperature over I2C/SPI.",
    lastRestocked: "11 days ago",
    createdAt: "2026-01-16",
    movementLogs: [
      {
        id: "log-113",
        type: "in",
        quantity: 140,
        reference: "PO-2026-015",
        timestamp: "2026-02-01 13:15",
        performedBy: "Alex Morgan",
        note: "Inbound sensor stock.",
      },
    ],
  },
  {
    id: "prod-12",
    sku: "ELEC-RP2-040",
    name: "Raspberry Pi RP2040 Microcontroller Board",
    category: "Electronics",
    currentStock: 86,
    minStock: 25,
    unit: "pcs",
    unitPrice: 4.2,
    warehouse: "Central Depot (WH-3)",
    status: "in_stock",
    barcode: "890123450012",
    supplier: "Pi Solutions",
    description: "Dual-core ARM Cortex-M0+ processor at 133MHz with 2MB flash and micro-USB port.",
    lastRestocked: "12 days ago",
    createdAt: "2026-01-17",
    movementLogs: [
      {
        id: "log-114",
        type: "in",
        quantity: 100,
        reference: "PO-2026-014",
        timestamp: "2026-01-31 10:20",
        performedBy: "Sarah Chen",
        note: "Pico board batch arrival.",
      },
    ],
  },
  {
    id: "prod-13",
    sku: "POW-SMPS-12V",
    name: "Switching Power Supply 12V 10A 120W",
    category: "Power",
    currentStock: 18,
    minStock: 20,
    unit: "units",
    unitPrice: 18.75,
    warehouse: "East Annex (WH-2)",
    status: "low_stock",
    barcode: "890123450013",
    supplier: "MeanWell Industrial",
    description: "Universal AC input enclosed switching power supply with short circuit/overload protection.",
    lastRestocked: "16 days ago",
    createdAt: "2026-01-19",
    movementLogs: [
      {
        id: "log-115",
        type: "out",
        quantity: 12,
        reference: "SO-2026-082",
        timestamp: "2026-02-07 15:30",
        performedBy: "Alex Morgan",
        note: "Delivered for test bench installations.",
      },
    ],
  },
  {
    id: "prod-14",
    sku: "SENS-TOF-VL53",
    name: "VL53L0X Time-of-Flight Distance Sensor",
    category: "Sensors",
    currentStock: 62,
    minStock: 20,
    unit: "pcs",
    unitPrice: 6.1,
    warehouse: "Main Hub (WH-1)",
    status: "in_stock",
    barcode: "890123450014",
    supplier: "SensorTech Micro",
    description: "Laser ranging sensor module capable of measuring up to 2m distance with millimetric precision.",
    lastRestocked: "10 days ago",
    createdAt: "2026-01-20",
    movementLogs: [
      {
        id: "log-116",
        type: "in",
        quantity: 75,
        reference: "PO-2026-019",
        timestamp: "2026-02-02 11:00",
        performedBy: "Sarah Chen",
        note: "Laser sensor batch receipt.",
      },
    ],
  },
  {
    id: "prod-15",
    sku: "CABL-FLAT-16P",
    name: "16-Pin IDC Flat Ribbon Cable (1.27mm Pitch) 5m",
    category: "Cables & Adapters",
    currentStock: 42,
    minStock: 15,
    unit: "m",
    unitPrice: 5.6,
    warehouse: "East Annex (WH-2)",
    status: "in_stock",
    barcode: "890123450015",
    supplier: "ConnectPro Global",
    description: "Flexible rainbow color-coded IDC ribbon cable for internal interconnects.",
    lastRestocked: "15 days ago",
    createdAt: "2026-01-22",
    movementLogs: [
      {
        id: "log-117",
        type: "in",
        quantity: 50,
        reference: "PO-2026-016",
        timestamp: "2026-01-28 14:15",
        performedBy: "Alex Morgan",
        note: "Ribbon spool replenishment.",
      },
    ],
  },
  {
    id: "prod-16",
    sku: "CONS-ISOP-1L",
    name: "Isopropyl Alcohol 99.9% High Purity 1 Liter",
    category: "Consumables",
    currentStock: 5,
    minStock: 15,
    unit: "tubes",
    unitPrice: 11.2,
    warehouse: "Main Hub (WH-1)",
    status: "low_stock",
    barcode: "890123450016",
    supplier: "LabChem Supplies",
    description: "Electronics grade IPA solvent for PCB degreasing and 3D print bed cleaning.",
    lastRestocked: "7 days ago",
    createdAt: "2026-01-23",
    movementLogs: [
      {
        id: "log-118",
        type: "out",
        quantity: 10,
        reference: "SO-2026-096",
        timestamp: "2026-02-11 16:00",
        performedBy: "Sarah Chen",
        note: "Cleanroom laboratory consumption.",
      },
    ],
  },
  {
    id: "prod-17",
    sku: "FILA-PETG-WHT",
    name: "PETG 3D Printer Filament 1.75mm White 1kg",
    category: "3D Printing",
    currentStock: 64,
    minStock: 25,
    unit: "spools",
    unitPrice: 21.0,
    warehouse: "Central Depot (WH-3)",
    status: "in_stock",
    barcode: "890123450017",
    supplier: "PolyForm Polymers",
    description: "Chemical and heat resistant PETG engineering thermoplastic filament.",
    lastRestocked: "5 days ago",
    createdAt: "2026-01-25",
    movementLogs: [
      {
        id: "log-119",
        type: "in",
        quantity: 80,
        reference: "PO-2026-029",
        timestamp: "2026-02-07 10:30",
        performedBy: "Alex Morgan",
        note: "PETG white filament stock order.",
      },
    ],
  },
  {
    id: "prod-18",
    sku: "TOOL-SOL-T12",
    name: "T12 Digital Smart Soldering Iron Station 72W",
    category: "Tools",
    currentStock: 22,
    minStock: 10,
    unit: "sets",
    unitPrice: 48.5,
    warehouse: "Main Hub (WH-1)",
    status: "in_stock",
    barcode: "890123450018",
    supplier: "WerkTool Instruments",
    description: "OLED display temperature adjustable (150-480C) rapid heating soldering station with stand.",
    lastRestocked: "13 days ago",
    createdAt: "2026-01-26",
    movementLogs: [
      {
        id: "log-120",
        type: "in",
        quantity: 25,
        reference: "PO-2026-017",
        timestamp: "2026-01-30 11:45",
        performedBy: "Sarah Chen",
        note: "Soldering iron station batch received.",
      },
    ],
  },
];
